name: CD reusable

on: 
  workflow_call:
    inputs:
      IMAGE_TAG:  
        description: 'RNG-Artifact-name'
        required: true
        type: string

  deployment:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: download image
        run: docker pull ${{ secrets.GH_TOKEN }}/gh_entregable:${{ steps.version.outputs.version }}

      - name: docker run
        run: docker run -d -p 8080:8080 ${{ secrets.GH_TOKEN }}/gh_entregable:${{ steps.version.outputs.version }}

      - name: curl
        run: |
          curl http://localhost:8080 >> result.html
          cat result.html
