env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches: main

jobs: 
  ci:
    runs-on: ubuntu-latest
    outputs: 
      IMAGE_TAG: ${{ steps.ci.outputs.IMAGE_TAG }}
    steps:
      - name: call_workflow_ci
        uses: ./.github/examen_autoria_luis/workflowCI.yaml
        id: ci
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: call_workflow_cd
        uses: ./.github/examen_autoria_luis/workflowCD.yaml
        with: 
          IMAGE_TAG: ${{ needs.ci.outputs.IMAGE_TAG }}
          REGISTRY: $REGISTRY
